spring:
  application:
    name: 'order-service'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/bookstore?useSSL=false&serverTimezone=UTC'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'

management:
  endpoints:
    web:
      exposure:
        include: '*'
      # base-path: '/manage'
  endpoint:
    health:
      show-details: 'ALWAYS'
      group:
        health-group:
          include: 'ping, diskSpace'
  info:
    env:
      enabled: true
    os:
      enabled: true

info:
  application:
    name: '@project.artifactId@'
    description: '@project.description@'
    project-version: '@project.version@'
    java-version: ${java.version}
